apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-security 
  namespace: argocd
spec:
  destination:
    namespace: spring-security 
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s 
    repoURL: https://github.com/AntonioDiSalvo/spring-security-tutorial-infra 
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
