apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-security
  name: spring-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-security
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-security
    spec:
      containers:
      - image: disalvoantonio/social:0.0.2-SNAPSHOT
        name: social
        resources: {}
        env:
          - name: githubClientId
            value: 98f1c204c75bef6de647
          - name: googleClientId
            value: 985966789883-9bf2eleno3fsq1o9r00uqva2tg8ksokg.apps.googleusercontent.com
status: {}
